### ISSUE TITLE
Split the “functional” and “global” API?

### ISSUE THREAD

**Issue by tomek-he-him** [1000ch/array-fill#2]
Hi, at the moment when I `require('array-fill')` I actually have my `Array.prototype` modified as well! There’s a good practice that a function _either_ returns a value _or_ causes side-effects. Any developer will want one or the other – never both. There are a couple of sneaky functions in the core library (like `Array.prototype.pop`) – but they come from the dark old ages of JS and many developers avoid them today.

There’s a great project by @ljharb https://github.com/es-shims/es-shim-api – he suggests a very reasonable API for polyfills. According to his guidelines:
- `const fill = require('array-fill')` should return a pure, self-coded function, and
- `require('array-fill/shim')` should modify the global object.

**Comment by 1000ch** [comment]
Agreed. I'll do so :+1:

**Comment by ljharb** [comment]
@1000ch When you do, please also be sure to include all of the test cases currently in `es6-shim` :-)

**Comment by 1000ch** [comment]
Fixed on 5ae068f.
